# Generated by Django 4.1.6 on 2023-02-08 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_tag_product_vote_ratio_product_vote_total_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featured_image',
            field=models.ImageField(blank=True, default="{% static 'images/pngtree-cartoon-character-avatar-free-illustration-image_1344683' %}", null=True, upload_to=''),
        ),
    ]
