# Generated by Django 4.1.6 on 2023-02-08 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='featured_image',
            field=models.ImageField(blank=True, default="{% static 'images/default.jpg' %}", null=True, upload_to=''),
        ),
    ]
